COUNTRIES_DATABASE = [
        {'abw': 'Aruba'},
        {'afg': 'Afeganistão'},
        {'ago': 'Angola'},
        {'aia': 'Anguilla'},
        {'ala': 'Ilhas Åland'},
        {'alb': 'Albânia'},
        {'and': 'Andorra'},
        {'are': 'Emirados Árabes Unidos'},
        {'arg': 'Argentina'},
        {'arm': 'Armênia'},
        {'asm': 'Samoa Americana'},
        {'ata': 'Antártida'},
        {'atf': 'Territórios Franceses do Sul'},
        {'atg': 'Antígua e Barbuda'},
        {'aus': 'Austrália'},
        {'aut': 'Áustria'},
        {'aze': 'Azerbaijão'},
        {'bdi': 'Burundi'},
        {'bel': 'Bélgica'},
        {'ben': 'Benim'},
        {'bfa': 'Burkina Faso'},
        {'bgd': 'Bangladesh'},
        {'bgr': 'Bulgária'},
        {'bhr': 'Bahrein'},
        {'bhs': 'Bahamas'},
        {'bih': 'Bósnia e Herzegovina'},
        {'blm': 'São Bartolomeu'},
        {'blr': 'Bielorrússia'},
        {'blz': 'Belize'},
        {'bmu': 'Bermuda'},
        {'bol': 'Bolívia'},
        {'bra': 'Brasil'},
        {'brb': 'Barbados'},
        {'brn': 'Brunei'},
        {'btn': 'Butão'},
        {'bvt': 'Ilha Bouvet'},
        {'bwa': 'Botsuana'},
        {'caf': 'República Centro-Africana'},
        {'can': 'Canadá'},
        {'che': 'Suíça'},
        {'chl': 'Chile'},
        {'chn': 'China'},
        {'civ': 'Costa do Marfim'},
        {'cmr': 'Camarões'},
        {'cod': 'República Democrática do Congo'},
        {'cog': 'Congo'},
        {'cok': 'Ilhas Cook'},
        {'col': 'Colômbia'},
        {'com': 'Comores'},
        {'cpv': 'Cabo Verde'},
        {'cri': 'Costa Rica'},
        {'cub': 'Cuba'},
        {'cuw': 'Curaçao'},
        {'cxr': 'Ilha Christmas'},
        {'cyp': 'Chipre'},
        {'cze': 'República Tcheca'},
        {'deu': 'Alemanha'},
        {'dji': 'Djibuti'},
        {'dma': 'Dominica'},
        {'dnk': 'Dinamarca'},
        {'dom': 'República Dominicana'},
        {'dza': 'Argélia'},
        {'ecu': 'Equador'},
        {'egy': 'Egito'},
        {'eri': 'Eritreia'},
        {'esp': 'Espanha'},
        {'est': 'Estônia'},
        {'eth': 'Etiópia'},
        {'fin': 'Finlândia'},
        {'fji': 'Fiji'},
        {'fra': 'França'},
        {'fro': 'Ilhas Faroé'},
        {'fsm': 'Micronésia'},
        {'gab': 'Gabão'},
        {'gbr': 'Reino Unido'},
        {'geo': 'Geórgia'},
        {'ggy': 'Guernsey'},
        {'gha': 'Gana'},
        {'gib': 'Gibraltar'},
        {'gin': 'Guiné'},
        {'gmb': 'Gâmbia'},
        {'gnb': 'Guiné-Bissau'},
        {'gnq': 'Guiné Equatorial'},
        {'grc': 'Grécia'},
        {'grd': 'Granada'},
        {'grl': 'Groenlândia'},
        {'gtm': 'Guatemala'},
        {'guf': 'Guiana Francesa'},
        {'guy': 'Guiana'},
        {'hnd': 'Honduras'},
        {'hrv': 'Croácia'},
        {'hti': 'Haiti'},
        {'hun': 'Hungria'},
        {'idn': 'Indonésia'},
        {'ind': 'Índia'},
        {'irl': 'Irlanda'},
        {'irn': 'Irã'},
        {'irq': 'Iraque'},
        {'isl': 'Islândia'},
        {'isr': 'Israel'},
        {'ita': 'Itália'},
        {'jam': 'Jamaica'},
        {'jey': 'Jersey'},
        {'jor': 'Jordânia'},
        {'jpn': 'Japão'},
        {'kaz': 'Cazaquistão'},
        {'ken': 'Quênia'},
        {'kgz': 'Quirguistão'},
        {'khm': 'Camboja'},
        {'kir': 'Quirguistão'},
        {'kna': 'São Cristóvão e Neves'},
        {'kor': 'Coreia do Sul'},
        {'kos': 'Kosovo'},
        {'kwt': 'Kuwait'},
        {'lao': 'Laos'},
        {'lbn': 'Líbano'},
        {'lbr': 'Libéria'},
        {'lby': 'Líbia'},
        {'lca': 'Santa Lúcia'},
        {'lie': 'Liechtenstein'},
        {'lka': 'Sri Lanka'},
        {'lso': 'Lesoto'},
        {'ltu': 'Lituânia'},
        {'lux': 'Luxemburgo'},
        {'lva': 'Letônia'},
        {'maf': 'São Martinho'},
        {'mar': 'Marrocos'},
        {'mco': 'Mônaco'},
        {'mda': 'Moldávia'},
        {'mdg': 'Madagascar'},
        {'mdv': 'Maldivas'},
        {'mex': 'México'},
        {'mhl': 'Ilhas Marshall'},
        {'mkd': 'Macedônia do Norte'},
        {'mli': 'Mali'},
        {'mlt': 'Malta'},
        {'mmr': 'Mianmar'},
        {'mne': 'Montenegro'},
        {'mng': 'Mongólia'},
        {'moz': 'Moçambique'},
        {'mrt': 'Mauritânia'},
        {'mtq': 'Martinica'},
        {'mus': 'Maurício'},
        {'mwi': 'Malawi'},
        {'mys': 'Malásia'},
        {'nam': 'Namíbia'},
        {'ncl': 'Nova Caledônia'},
        {'ner': 'Níger'},
        {'nga': 'Nigéria'},
        {'nic': 'Nicarágua'},
        {'niu': 'Niue'},
        {'nld': 'Países Baixos'},
        {'nor': 'Noruega'},
        {'npl': 'Nepal'},
        {'nru': 'Nauru'},
        {'nzl': 'Nova Zelândia'},
        {'omn': 'Omã'},
        {'pak': 'Paquistão'},
        {'pan': 'Panamá'},
        {'per': 'Peru'},
        {'phl': 'Filipinas'},
        {'plw': 'Palau'},
        {'png': 'Papua-Nova Guiné'},
        {'pol': 'Polônia'},
        {'pri': 'Porto Rico'},
        {'prk': 'Coreia do Norte'},
        {'prt': 'Portugal'},
        {'pry': 'Paraguai'},
        {'pse': 'Palestina'},
        {'qat': 'Catar'},
        {'rou': 'Romênia'},
        {'rus': 'Rússia'},
        {'rwa': 'Ruanda'},
        {'sau': 'Arábia Saudita'},
        {'sdn': 'Sudão'},
        {'sen': 'Senegal'},
        {'sgp': 'Singapura'},
        {'slb': 'Ilhas Salomão'},
        {'sle': 'Serra Leoa'},
        {'slv': 'El Salvador'},
        {'smr': 'San Marino'},
        {'som': 'Somália'},
        {'srb': 'Sérvia'},
        {'ssd': 'Sudão do Sul'},
        {'stp': 'São Tomé e Príncipe'},
        {'sur': 'Suriname'},
        {'svk': 'Eslováquia'},
        {'svn': 'Eslovênia'},
        {'swe': 'Suécia'},
        {'swz': 'Eswatini'},
        {'syc': 'Seicheles'},
        {'syr': 'Síria'},
        {'tcd': 'Chade'},
        {'tgo': 'Togo'},
        {'tha': 'Tailândia'},
        {'tjk': 'Tajiquistão'},
        {'tkl': 'Tokelau'},
        {'tkm': 'Turcomenistão'},
        {'tls': 'Timor-Leste'},
        {'ton': 'Tonga'},
        {'tto': 'Trinidad e Tobago'},
        {'tun': 'Tunísia'},
        {'tur': 'Turquia'},
        {'tuv': 'Tuvalu'},
        {'twn': 'Taiwan'},
        {'tza': 'Tanzânia'},
        {'uga': 'Uganda'},
        {'ukr': 'Ucrânia'},
        {'ury': 'Uruguai'},
        {'usa': 'Estados Unidos'},
        {'uzb': 'Uzbequistão'},
        {'vat': 'Vaticano'},
        {'vct': 'São Vicente e Granadinas'},
        {'ven': 'Venezuela'},
        {'vir': 'Ilhas Virgens'},
        {'vnm': 'Vietnã'},
        {'vut': 'Vanuatu'},
        {'wsm': 'Samoa'},
        {'yem': 'Iêmen'},
        {'zaf': 'África do Sul'},
        {'zmb': 'Zâmbia'},
        {'zwe': 'Zimbábue'},
    ]