COUNTRIES_DATABASE = [
        {'afg': 'Afeganistão'}, {'alb': 'Albânia'}, {'dza': 'Argélia'}, {'and': 'Andorra'},
        {'ago': 'Angola'}, {'atg': 'Antígua e Barbuda'}, {'arg': 'Argentina'}, {'arm': 'Armênia'},
        {'aus': 'Austrália'}, {'aut': 'Áustria'}, {'aze': 'Azerbaijão'}, {'bhs': 'Bahamas'},
        {'bhr': 'Bahrein'}, {'bgd': 'Bangladesh'}, {'brb': 'Barbados'}, {'blr': 'Bielorrússia'},
        {'bel': 'Bélgica'}, {'blz': 'Belize'}, {'ben': 'Benim'},
        {'bol': 'Bolívia'}, {'bih': 'Bósnia e Herzegovina'}, {'bwa': 'Botsuana'}, {'bra': 'Brasil'},
        {'brn': 'Brunei'}, {'bgr': 'Bulgária'}, {'bfa': 'Burkina Faso'}, {'bdi': 'Burundi'},
        {'cpv': 'Cabo Verde'}, {'khm': 'Camboja'}, {'cmr': 'Camarões'}, {'can': 'Canadá'},
        {'caf': 'República Centro-Africana'}, {'tcd': 'Chade'}, {'chl': 'Chile'}, {'chn': 'China'},
        {'col': 'Colômbia'}, {'com': 'Comores'}, {'cog': 'Congo'}, {'cod': 'República Democrática do Congo'},
        {'cri': 'Costa Rica'}, {'hrv': 'Croácia'}, {'cub': 'Cuba'}, {'cyp': 'Chipre'},
        {'cze': 'República Tcheca'}, {'dnk': 'Dinamarca'}, {'dji': 'Djibuti'}, {'dma': 'Dominica'},
        {'dom': 'República Dominicana'}, {'ecu': 'Equador'}, {'egy': 'Egito'}, {'slv': 'El Salvador'},
        {'gnq': 'Guiné Equatorial'}, {'eri': 'Eritreia'}, {'est': 'Estônia'}, {'swz': 'Eswatini'},
        {'eth': 'Etiópia'}, {'fji': 'Fiji'}, {'fin': 'Finlândia'}, {'fra': 'França'}, {"guf": "Guiana Francesa"},
        {'gab': 'Gabão'}, {'gmb': 'Gâmbia'}, {'geo': 'Geórgia'}, {'deu': 'Alemanha'},
        {'gha': 'Gana'}, {'grc': 'Grécia'}, {'grd': 'Granada'}, {'gtm': 'Guatemala'},
        {'gin': 'Guiné'}, {'gnb': 'Guiné-Bissau'}, {'guy': 'Guiana'}, {'hti': 'Haiti'},
        {'hnd': 'Honduras'}, {'hun': 'Hungria'}, {'isl': 'Islândia'}, {'ind': 'Índia'},
        {'idn': 'Indonésia'}, {'irn': 'Irã'}, {'irq': 'Iraque'}, {'irl': 'Irlanda'},
        {'isr': 'Israel'}, {'ita': 'Itália'}, {'jam': 'Jamaica'}, {'jpn': 'Japão'},
        {'jor': 'Jordânia'}, {'kaz': 'Cazaquistão'}, {'ken': 'Quênia'}, {'kir': 'Quirguistão'},
        {'prk': 'Coreia do Norte'}, {'kor': 'Coreia do Sul'}, {'kwt': 'Kuwait'}, {'kgz': 'Quirguistão'},
        {'lao': 'Laos'}, {'lva': 'Letônia'}, {'lbn': 'Líbano'}, {'lso': 'Lesoto'},
        {'lbr': 'Libéria'}, {'lby': 'Líbia'}, {'lie': 'Liechtenstein'}, {'ltu': 'Lituânia'},
        {'lux': 'Luxemburgo'}, {'mdg': 'Madagascar'}, {'mwi': 'Malawi'}, {'mys': 'Malásia'},
        {'mdv': 'Maldivas'}, {'mli': 'Mali'}, {'mlt': 'Malta'}, {'mhl': 'Ilhas Marshall'},
        {'mrt': 'Mauritânia'}, {'mus': 'Maurício'}, {'mex': 'México'}, {'fsm': 'Micronésia'},
        {'mda': 'Moldávia'}, {'mco': 'Mônaco'}, {'mng': 'Mongólia'}, {'mne': 'Montenegro'},
        {'mar': 'Marrocos'}, {'moz': 'Moçambique'}, {'mmr': 'Mianmar'}, {'nam': 'Namíbia'},
        {'nru': 'Nauru'}, {'npl': 'Nepal'}, {'nld': 'Países Baixos'}, {'nzl': 'Nova Zelândia'},
        {'nic': 'Nicarágua'}, {'ner': 'Níger'}, {'nga': 'Nigéria'}, {'mkd': 'Macedônia do Norte'},
        {'nor': 'Noruega'}, {'omn': 'Omã'}, {'pak': 'Paquistão'}, {'plw': 'Palau'},
        {'pan': 'Panamá'}, {'png': 'Papua-Nova Guiné'}, {'pry': 'Paraguai'}, {'per': 'Peru'},
        {'phl': 'Filipinas'}, {'pol': 'Polônia'}, {'prt': 'Portugal'}, {'qat': 'Catar'},
        {'rou': 'Romênia'}, {'rus': 'Rússia'}, {'rwa': 'Ruanda'}, {'kna': 'São Cristóvão e Neves'},
        {'lca': 'Santa Lúcia'}, {'vct': 'São Vicente e Granadinas'}, {'wsm': 'Samoa'},
        {'smr': 'San Marino'}, {'stp': 'São Tomé e Príncipe'}, {'sau': 'Arábia Saudita'},
        {'sen': 'Senegal'}, {'srb': 'Sérvia'}, {'syc': 'Seicheles'}, {'sle': 'Serra Leoa'},
        {'sgp': 'Singapura'}, {'svk': 'Eslováquia'}, {'svn': 'Eslovênia'}, {'slb': 'Ilhas Salomão'},
        {'som': 'Somália'}, {'zaf': 'África do Sul'}, {'ssd': 'Sudão do Sul'}, {'esp': 'Espanha'},
        {'lka': 'Sri Lanka'}, {'sdn': 'Sudão'}, {'sur': 'Suriname'}, {'swe': 'Suécia'},
        {'che': 'Suíça'}, {'syr': 'Síria'}, {'twn': 'Taiwan'}, {'tjk': 'Tajiquistão'},
        {'tza': 'Tanzânia'}, {'tha': 'Tailândia'}, {'tls': 'Timor-Leste'}, {'tgo': 'Togo'},
        {'ton': 'Tonga'}, {'tto': 'Trinidad e Tobago'}, {'tun': 'Tunísia'}, {'tur': 'Turquia'},
        {'tkm': 'Turcomenistão'}, {'tuv': 'Tuvalu'}, {'uga': 'Uganda'}, {'ukr': 'Ucrânia'},
        {'are': 'Emirados Árabes Unidos'}, {'gbr': 'Reino Unido'}, {'usa': 'Estados Unidos'},
        {'ury': 'Uruguai'}, {'uzb': 'Uzbequistão'}, {'vut': 'Vanuatu'}, {'vat': 'Vaticano'},
        {'ven': 'Venezuela'}, {'vnm': 'Vietnã'}, {'yem': 'Iêmen'}, {'zmb': 'Zâmbia'},
        {'zwe': 'Zimbábue'}, {'pse': 'Palestina'}, {'kos': 'Kosovo'}
    ]